workflows:
  my-workflow:
    instance_type: mac_mini
    scripts:
      - name: Setup Bulldozer and load Android SDK
        script: |
                  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                  sudo ln -sfn /usr/local/opt/openssl /usr/local/ssl
                  brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer autoconf automake
                  python3 -m pip install --upgrade pip
                  pip3 install --user --upgrade buildozer cython kivy aiohttp kivymd asynckivy virtualenv kivy-ios
                  mkdir /Users/builder/.buildozer
                  mkdir /Users/builder/.buildozer/android 
                  mkdir /Users/builder/.buildozer/android/platform 
                  mkdir /Users/builder/.buildozer/android/platform/android-sdk
                  yes | /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
                  /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "ndk;23.2.8568313"
                  /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --install "cmake;3.18.1"
                  /usr/local/share/android-sdk/cmdline-tools/latest/bin/sdkmanager --update
                  rsync -a /usr/local/share/android-sdk/. /Users/builder/.buildozer/android/platform/android-sdk
                  ls
                  
      - name: Run Buildozer
        script: |
                  buildozer android release
                  buildozer ios release

    artifacts:
      - ./bin/*.aab
      - ./bin/*.apk
      - ./bin/*.aar
      - ./bin/*.app
      - ./bin/*.ipa
      - ./bin/*.pkg
      - ./bin/*.jar
      - ./bin/*.zip
      - ./bin/*.xarchive