workflows:
  Build App For IOS and ANDROID:
    instance_type: mac_mini
    scripts:
      - name: Download Required Packages
        script: |
                  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
                  echo "----------------------------------------------------------------------------------"
                  sudo ln -sfn /usr/local/opt/openssl /usr/local/ssl
                  echo "----------------------------------------------------------------------------------"
                  brew install pkg-config sdl2 sdl2_image sdl2_ttf sdl2_mixer gstreamer autoconf automake 
                  echo "----------------------------------------------------------------------------------"
                  python3 -m pip install --upgrade pip
                  echo "----------------------------------------------------------------------------------"
                  pip3 install --user --upgrade buildozer cython kivy aiohttp kivymd asynckivy virtualenv kivy-ios
                  echo "----------------------------------------------------------------------------------"


      - name: Remove Unused Files
        script: |
                  sudo rm -r $HOME/programs/flutter
                  sudo rm /Applications/Xcode-13.3.app
                  sudo rm /Applications/Xcode-14.0.app
                  sudo rm -r /Users/builder/.android/avd/emulator.avd
                  sudo rm -r /Library/Java/JavaVirtualMachines/zulu-18.jdk
                  sudo rm -r /Library/Java/JavaVirtualMachines/zulu-16.jdk
                  sudo rm -r /Library/Java/JavaVirtualMachines/zulu-11.jdk
                  export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/Home
                  java -version
 
      - name: Run Buildozer
        script: |
                  export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk
                  buildozer android release || { echo 'ANDROID FAILIURE' ; exit 1; }
                  echo "----------------------------------------------------------------------------------"
                  buildozer ios release || { echo 'IOS FAILIURE' ; exit 1; }

    artifacts:
      - ./bin/*.aab
      - ./bin/*.apk
      - ./bin/*.aar
      - ./bin/*.app
      - ./bin/*.ipa
      - ./bin/*.pkg
      - ./bin/*.jar
      - ./bin/*.zip
      - ./bin/*.xarchive