workflows:
  my-workflow:
    instance_type: mac_mini
    scripts:
      - name: Setup Bulldozer
        script: |
                  pip3 install --user --upgrade buildozer cython kivy aiohttp kivymd asynckivy virtualenv
                  buildozer android release
                  
